name: 'Build Debian package on multiple architectures'
description: 'Build Debian package on multiple architectures'
inputs:
  sources:
    description: 'Any extra sources to add to apt'
    required: false
    default: ''
  ppa:
    description: 'An extra PPA to add to apt (no ppa: prefix)'
    required: false
    default: ''
  args:
    description: 'Arguments to pass to dpkg-buildpackage'
    required: false
  platform:
    description: 'Target architecture'
    required: false
    default: 'amd64'

runs:
  using: 'composite'
  steps:
    - name: Setup QEMU
      if: ${{ !contains(inputs.platform, 'amd64') }}
      uses: docker/setup-qemu-action@v3
    - name: Build Debian package
      run: |
        if [ ! -d "_gh-action-build-deb" ]; then
          mkdir _gh-action-build-deb
          cd _gh-action-build-deb
          curl -LO https://raw.githubusercontent.com/andy5995/gh-action-build-deb/refs/tags/latest/entrypoint.sh
          cd
        fi
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          --platform linux/${{ inputs.platform }} \
          -e INPUT_SOURCES="${{ inputs.sources }}" \
          -e INPUT_PPA="${{ inputs.ppa }}" \
          -e INPUT_ARGS="${{ inputs.args }}" \
          ghcr.io/andy5995/gh-action-build-deb:bookworm
      shell: bash

branding:
  icon: 'package'
  color: 'gray-dark'
