name: Test Action
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: trunk
    paths:
    - 'entrypoint.sh'
    - '**Dockerfile'
    - '!**.yml'
    - '!**.md'
    - 'action.yml'
    - '**test.yml'

jobs:
  build-deb:
    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    runs-on: ubuntu-latest
    env:
      ACTION_DIR: '_action_test'
    steps:
    - name: Checkout rmw
      uses: actions/checkout@v4
      with:
        repository: theimpossibleastronaut/rmw
        ref: v0.9.2

    - name: Copy debian directory
      run: cp -a packaging/debian .

    - uses: actions/checkout@v4
      with:
        path: ${{ env.ACTION_DIR }}
        fetch-depth: 0

    - name: Check if Dockerfile or entrypoint.sh has changed
      run: |
        cd $ACTION_DIR
        FILES=$(git log -1 -p ./ | grep +++ | cut -d '/' -f 2-| sed -e 's|dev/null||g')
        if echo "$FILES" | grep -qE "^(Dockerfile|entrypoint.sh)$"; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Set up QEMU
      if: ${{ matrix.platform != 'amd64' && env.changed == 'true' }}
      uses: docker/setup-qemu-action@v3

    - name: Build docker image
      if: ${{ env.changed == 'true' }}
      run: |
        cd "$ACTION_DIR"
        docker build \
          --platform linux/${{ matrix.platform }} \
          -t ghcr.io/${{ github.repository_owner }}/gh-action-build-deb:bookworm \
          .

# Apparently variables aren't allowed with the 'uses' key?
#
# Invalid workflow file: .github/workflows/test.yml#L47
# The workflow is not valid. .github/workflows/test.yml (Line: 47, Col: 13):
# Unrecognized named-value: 'env'. Located at position 1 within expression: env.ACTION_DIR
    - uses: ./_action_test
      with:
        args: |
          --no-sign
          --compression=xz
        platform: ${{ matrix.platform }}

    - name: Create sha256sum
      run: |
        DEB_FILENAME=$(basename `find output/*deb`)
        echo "DEB_FILENAME=$DEB_FILENAME" >> $GITHUB_ENV
        cd output
        sha256sum "$DEB_FILENAME" > "../$DEB_FILENAME.sha256sum"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEB_FILENAME }}
        path: |
          output/*.deb
          *deb.sha256sum
        if-no-files-found: error
